/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 24-okt-2018 13:06:41 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

/* Drop Tables */

DROP TABLE IF EXISTS Tootaja_seisundi_liik CASCADE
;

DROP TABLE IF EXISTS Parklakoha_kategooria_tyyp CASCADE
;

DROP TABLE IF EXISTS Parklakoha_kategooria CASCADE
;

DROP TABLE IF EXISTS Parklakoha_seisundi_liik CASCADE
;

DROP TABLE IF EXISTS Riik CASCADE
;

DROP TABLE IF EXISTS Isiku_seisundi_liik CASCADE
;

DROP TABLE IF EXISTS Kliendi_seisundi_liik CASCADE
;

DROP TABLE IF EXISTS Parkla CASCADE
;

DROP TABLE IF EXISTS Amet CASCADE
;

DROP TABLE IF EXISTS Isik CASCADE
;

DROP TABLE IF EXISTS Klient CASCADE
;

DROP TABLE IF EXISTS Tootaja CASCADE
;

DROP TABLE IF EXISTS Parklakoha_kategooria_omamine CASCADE
;

DROP TABLE IF EXISTS Parklakoht CASCADE
;

/* Create Tables */

CREATE TABLE Tootaja_seisundi_liik
(
	tootaja_seisundi_liik_kood smallint NOT NULL,
	nimetus varchar(50)	 NOT NULL,
	CONSTRAINT PK_Tootaja_seisundi_liik PRIMARY KEY (tootaja_seisundi_liik_kood),
	CONSTRAINT AK_Tootaja_seisundi_liik_nimetus UNIQUE (nimetus),
	CONSTRAINT CHK_Tootaja_seisundi_liik_nim_ei_ole_tyhi_v_ainult_tyhikud CHECK (nimetus!~'^[[:space:]]*$')
)
;

CREATE TABLE Parklakoha_kategooria_tyyp
(
	parklakoha_kategooria_tyyp_kood smallint NOT NULL,
	nimetus varchar(50)	 NOT NULL,
	CONSTRAINT PK_Parklakoha_kategooria_tyyp PRIMARY KEY (parklakoha_kategooria_tyyp_kood),
	CONSTRAINT AK_Parklakoha_kategooria_tyyp_nimetus UNIQUE (nimetus),
	CONSTRAINT CHK_Parklakoha_kategooria_tyyp_nimetus_ei_ole_tyhi_ CHECK (nimetus!~'^[[:space:]]*$')
)
;

CREATE TABLE Parklakoha_kategooria
(
	parklakoha_kategooria_kood smallint NOT NULL,
	parklakoha_kategooria_tyyp_kood smallint NOT NULL,
	nimetus varchar(50)	 NOT NULL,
	CONSTRAINT PK_Parklakoha_kategooria PRIMARY KEY (parklakoha_kategooria_kood),
	CONSTRAINT AK_parklakoha_kat_nimetus_parklakoha_kat_tyyp_kood UNIQUE (nimetus,parklakoha_kategooria_tyyp_kood),
	CONSTRAINT CHK_Parklakoha_kategooria_nim_ei_ole_tyhi_v_ainult_tyhikud CHECK (nimetus!~'^[[:space:]]*$'),
	CONSTRAINT FK_Parklakoha_kategooria_Parklakoha_kategooria_tyyp FOREIGN KEY (parklakoha_kategooria_tyyp_kood) REFERENCES Parklakoha_kategooria_tyyp (parklakoha_kategooria_tyyp_kood) ON DELETE No Action ON UPDATE Cascade
)
;

CREATE TABLE Parklakoha_seisundi_liik
(
	parklakoha_seisundi_liik_kood smallint NOT NULL,
	nimetus varchar(50)	 NOT NULL,
	CONSTRAINT PK_Parklakoha_seisundi_liik PRIMARY KEY (parklakoha_seisundi_liik_kood),
	CONSTRAINT AK_Parklakoha_seisundi_liik_nimetus UNIQUE (nimetus),
	CONSTRAINT CHK_Parklakoha_seisundi_liik_nim_ei_ole_tyhi_v_ainult_tyhikud CHECK (nimetus!~'^[[:space:]]*$')
)
;

CREATE TABLE Riik
(
	riik_kood char(3)	 NOT NULL,
	nimetus varchar(50)	 NOT NULL,
	CONSTRAINT PK_Riik PRIMARY KEY (riik_kood),
	CONSTRAINT AK_Riik_nimetus UNIQUE (nimetus),
	CONSTRAINT CHK_Riik_riik_kood_formaat_oige CHECK (riik_kood ~ '^[A-Z]{3}$'),
	CONSTRAINT CHK_Riik_nim_ei_ole_tyhi_v_ainult_tyhikud CHECK (nimetus!~'^[[:space:]]*$')
)
;

CREATE TABLE Isiku_seisundi_liik
(
	isiku_seisundi_liik_kood smallint NOT NULL,
	nimetus varchar(50)	 NOT NULL,
	CONSTRAINT PK_Isiku_seisundi_liik PRIMARY KEY (isiku_seisundi_liik_kood),
	CONSTRAINT AK_Isiku_seisundi_liik_nimetus UNIQUE (nimetus),
	CONSTRAINT CHK_Isiku_seisundi_liik_nim_ei_ole_tyhi_v_ainult_tyhikud CHECK (nimetus!~'^[[:space:]]*$')
)
;

CREATE TABLE Kliendi_seisundi_liik
(
	kliendi_seisundi_liik_kood smallint NOT NULL,
	nimetus varchar(50)	 NOT NULL,
	CONSTRAINT PK_Kliendi_seisundi_liik PRIMARY KEY (kliendi_seisundi_liik_kood),
	CONSTRAINT AK_Kliendi_seisundi_liik_nimetus UNIQUE (nimetus),
	CONSTRAINT CHK_Kliendi_seisundi_liik_nim_ei_ole_tyhi_v_ainult_tyhikud CHECK (nimetus!~'^[[:space:]]*$')
)
;

CREATE TABLE Parkla
(
	parkla_kood integer NOT NULL,
	nimetus varchar(50)	 NOT NULL,
	CONSTRAINT PK_Parkla PRIMARY KEY (parkla_kood),
	CONSTRAINT AK_Parkla_nimetus UNIQUE (nimetus),
	CONSTRAINT CHK_Parkla_nim_ei_ole_tyhi_v_ainult_tyhikud CHECK (nimetus!~'^[[:space:]]*$')
)
;

CREATE TABLE Amet
(
	amet_kood smallint NOT NULL,
	nimetus varchar(50)	 NOT NULL,
	kirjeldus text NULL,
	CONSTRAINT PK_Amet PRIMARY KEY (amet_kood),
	CONSTRAINT AK_Amet_nimetus UNIQUE (nimetus),
	CONSTRAINT CHK_Amet_kirjeldus_ei_ole_tyhi_v_ainult_tyhikud CHECK (kirjeldus!~'^[[:space:]]*$'),
	CONSTRAINT CHK_Amet_nim_ei_ole_tyhi_v_ainult_tyhikud CHECK (nimetus!~'^[[:space:]]*$')
)
;

CREATE TABLE Isik
(
	isik_id serial NOT NULL,
	isiku_seisundi_liik_kood smallint NOT NULL DEFAULT 1,
	riik_kood char(3)	 NOT NULL,
	isikukood varchar(50)	 NOT NULL,
	e_meil varchar(254)	 NOT NULL,
	parool varchar(60)	 NOT NULL,
	synni_kp date NOT NULL,
	reg_aeg timestamp NOT NULL DEFAULT localtimestamp(0),
	eesnimi varchar(1000)	 NULL,
	perenimi varchar(1000)	 NULL,
	elukoht varchar(255)	 NULL,
	CONSTRAINT PK_Isik PRIMARY KEY (isik_id),
	CONSTRAINT AK_Isik_e_meil UNIQUE (e_meil),
	CONSTRAINT AK_Isik_isikukood_riik_kood UNIQUE (isikukood,riik_kood),
	CONSTRAINT CHK_Isik_isikukood_lubatud_margid CHECK (isikukood ~ '^[a-zA-Z0-9[:space:]-/]*$'),
	CONSTRAINT CHK_Isik_isikukood_ei_ole_tyhi_v_ainult_tyhik CHECK (isikukood!~'^[[:space:]]*$'),
	CONSTRAINT CHK_Isik_e_meil_formaat_oige CHECK (e_meil ~ '^[a-zA-Z0-9.!#$%&''*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$'),
	CONSTRAINT CHK_Isik_synni_kp_vahemik_1900_01_01_ja_2100_12_31 CHECK (synni_kp >= '1900-01-01' AND synni_kp <= '2100-12-31'),
	CONSTRAINT CHK_Isik_reg_aeg_vahemalt_2010_01_01_vaiksem_2101_01_01 CHECK (reg_aeg >= '2010-01-01' AND reg_aeg < '2101-01-01'),
	CONSTRAINT CHK_Isik_eesnimi_v_perenimi_olemasolu CHECK (eesnimi IS NOT NULL OR perenimi IS NOT NULL ),
	CONSTRAINT CHK_Isik_eesnimi_ei_ole_tyhi_v_ainult_tyhikud CHECK (eesnimi!~'^[[:space:]]*$'),
	CONSTRAINT CHK_Isik_perenimi_ei_ole_tyhi_v_ainult_tyhikud CHECK (perenimi!~'^[[:space:]]*$'),
	CONSTRAINT CHK_Isik_elukoht_ei_ole_tyhi_v_ainult_tyhikud CHECK (elukoht!~'^[[:space:]]*$'),
	CONSTRAINT CHK_Isik_synni_kp_vaiksem_kui_reg_aeg CHECK (synni_kp <= reg_aeg),
	CONSTRAINT CHK_Isik_elukoht_ei_koosne_ainult_numbritest CHECK (elukoht!~'^[[:digit:]]*$'),
	CONSTRAINT FK_Isik_Isiku_seisundi_liik FOREIGN KEY (isiku_seisundi_liik_kood) REFERENCES Isiku_seisundi_liik (isiku_seisundi_liik_kood) ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT FK_Isik_Riik FOREIGN KEY (riik_kood) REFERENCES Riik (riik_kood) ON DELETE No Action ON UPDATE Cascade
)
;

CREATE TABLE Klient
(
	isik_id integer NOT NULL,
	kliendi_seisundi_liik_kood smallint NOT NULL DEFAULT 1,
	on_nous_tylitamisega boolean NOT NULL DEFAULT false,
	CONSTRAINT PK_Klient PRIMARY KEY (isik_id),
	CONSTRAINT FK_Klient_Kliendi_seisundi_liik FOREIGN KEY (kliendi_seisundi_liik_kood) REFERENCES Kliendi_seisundi_liik (kliendi_seisundi_liik_kood) ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT FK_Klient_Isik FOREIGN KEY (isik_id) REFERENCES Isik (isik_id) ON DELETE Cascade ON UPDATE No Action
)
;

CREATE TABLE Tootaja
(
	isik_id integer NOT NULL,
	amet_kood smallint NOT NULL,
	tootaja_seisundi_liik_kood smallint NOT NULL DEFAULT 1,
	mentor integer NULL,
	CONSTRAINT PK_Tootaja PRIMARY KEY (isik_id),
	CONSTRAINT CHK_Tootaja_tootaja_pole_enda_mentor CHECK (isik_id!=mentor),
	CONSTRAINT FK_Tootaja_Amet FOREIGN KEY (amet_kood) REFERENCES Amet (amet_kood) ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT FK_Tootaja_Tootaja_seisundi_liik FOREIGN KEY (tootaja_seisundi_liik_kood) REFERENCES Tootaja_seisundi_liik (tootaja_seisundi_liik_kood) ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT FK_Tootaja_Isik FOREIGN KEY (isik_id) REFERENCES Isik (isik_id) ON DELETE Cascade ON UPDATE No action,
	CONSTRAINT FK_Tootaja_mentor FOREIGN KEY (mentor) REFERENCES Tootaja (isik_id) ON DELETE Set Null ON UPDATE No Action
)
;


CREATE TABLE Parklakoht
(
	parklakoha_kood integer NOT NULL,
	isik_id integer NOT NULL,
	reg_aeg timestamp NOT NULL DEFAULT localtimestamp(0),
	parkimine_tund_hind decimal(4,2) NOT NULL,
	pindala_m2 decimal(4,2) NOT NULL,
	parkla_kood integer NOT NULL,
	parklakoha_seisundi_liik_kood smallint NOT NULL DEFAULT 1,
	kommentaar varchar(500)	 NULL,
	CONSTRAINT PK_Parklakoht PRIMARY KEY (parklakoha_kood),
	CONSTRAINT CHK_Parklakoht_reg_aeg_vahemalt_2010_01_01_vaiksem_2101_01_01 CHECK (reg_aeg >= '2010-01-01' AND reg_aeg < '2101-01-01'),
	CONSTRAINT CHK_Parklakoht_kommentaar_ei_ole_tyhi_v_ainult_tyhikud CHECK (kommentaar!~'^[[:space:]]*$'),
	CONSTRAINT CHK_Parklakoht_parkimine_tund_hind_positiivne CHECK (parkimine_tund_hind > 0),
	CONSTRAINT CHK_Parklakoht_pindala_m2_positiivne CHECK (pindala_m2 > 0),
	CONSTRAINT FK_Parklakoht_Tootaja FOREIGN KEY (isik_id) REFERENCES Tootaja (isik_id) ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT FK_Parklakoht_Parklakoha_seisundi_liik FOREIGN KEY (parklakoha_seisundi_liik_kood) REFERENCES Parklakoha_seisundi_liik (parklakoha_seisundi_liik_kood) ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT FK_Parklakoht_Parkla FOREIGN KEY (parkla_kood) REFERENCES Parkla (parkla_kood) ON DELETE No Action ON UPDATE Cascade
)
;

CREATE TABLE Parklakoha_kategooria_omamine
(
	parklakoha_kood integer NOT NULL,
	parklakoha_kategooria_kood smallint NOT NULL,
	CONSTRAINT PK_Parklakoha_kategooria_omamine PRIMARY KEY (parklakoha_kood,parklakoha_kategooria_kood),
	CONSTRAINT FK_Parklakoha_kategooria_omamine_Parklakoht FOREIGN KEY (parklakoha_kategooria_kood) REFERENCES Parklakoht (parklakoha_kood) ON DELETE Cascade ON UPDATE Cascade
)
;

/* Create Table Comments, Sequences for Autonumber Columns */



/* Create Primary Keys, Indexes, Uniques, Checks */

CREATE INDEX IXFK_Parklakoha_kategooria_Parklakoha_kategooria_tyyp ON Parklakoha_kategooria (parklakoha_kategooria_tyyp_kood ASC)
;

CREATE INDEX IXFK_Isik_Isiku_seisundi_liik ON Isik (isiku_seisundi_liik_kood ASC)
;

CREATE INDEX IXFK_Isik_Riik ON Isik (riik_kood ASC)
;

CREATE INDEX IXFK_Klient_Kliendi_seisundi_liik ON Klient (kliendi_seisundi_liik_kood ASC)
;

CREATE INDEX IXFK_Tootaja_Amet ON Tootaja (amet_kood ASC)
;

CREATE INDEX IXFK_Tootaja_Tootaja_seisundi_liik ON Tootaja (tootaja_seisundi_liik_kood ASC)
;

CREATE INDEX IXFK_Tootaja_Mentor ON Tootaja (mentor ASC)
;

CREATE INDEX IXFK_Parklakoha_kategooria_omamine_Parklakoht ON Parklakoha_kategooria_omamine (parklakoha_kategooria_kood ASC)
;

CREATE INDEX IXFK_Parklakoht_Parkla ON Parklakoht (parkla_kood ASC)
;

CREATE INDEX IXFK_Parklakoht_Parklakoha_seisundi_liik ON Parklakoht (parklakoha_seisundi_liik_kood ASC)
;

CREATE INDEX IXFK_Parklakoht_Tootaja ON Parklakoht (isik_id ASC)
;

