REVOKE ALL ON TABLE public.aktiivsed_ja_mitteaktiivsed_lauad FROM t164416;
REVOKE ALL ON TABLE public.koik_lauad FROM t164416;
REVOKE ALL ON TABLE public.koik_lauad_jsonis FROM t164416;
REVOKE ALL ON TABLE public.laudade_koondaruanne FROM t164416;
REVOKE ALL ON TABLE public.laudade_kategooriad FROM t164416;
REVOKE ALL ON TABLE public.laudade_pingeread FROM t164416;
REVOKE ALL PRIVILEGES ON FUNCTION f_lopeta_laud FROM t164416_juhataja;
REVOKE SELECT ON TABLE public.aktiivsed_ja_mitteaktiivsed_lauad FROM t164416_juhataja;
REVOKE SELECT ON TABLE public.koik_lauad FROM t164416_juhataja;
REVOKE SELECT ON TABLE public.koik_lauad_jsonis FROM t164416_juhataja;
REVOKE SELECT ON TABLE public.laudade_koondaruanne FROM t164416_juhataja;
REVOKE SELECT ON TABLE public.laudade_kategooriad FROM t164416_juhataja;
REVOKE SELECT ON TABLE public.laudade_pingeread FROM t164416_juhataja;
REVOKE EXECUTE ON FUNCTION f_lopeta_laud FROM t164416;
REVOKE EXECUTE ON FUNCTION public.f_kustuta_laud() FROM t164416;
REVOKE EXECUTE ON FUNCTION public.f_muuda_laua_seisundi_liik() FROM t164416;
REVOKE EXECUTE ON FUNCTION public.f_muuda_laud_aktiivseks() FROM t164416;
REVOKE ALL PRIVILEGES ON FUNCTION f_on_juhataja FROM t164416_juhataja;
REVOKE EXECUTE ON FUNCTION f_on_juhataja FROM t164416;
